### ISSUE TITLE
Integrity constraint violation: 1217 Cannot delete or upda     te a parent row: a foreign key constraint fails (SQL: drop table `contacts`)

### ISSUE THREAD

**Issue by ghermans** [idevelopment/Hcrm#120]
When running the command **artisan migrate:refresh** 

> [Illuminate\Database\QueryException]                                         
>   SQLSTATE[23000]: Integrity constraint violation: 1217 Cannot delete or upda  
>   te a parent row: a foreign key constraint fails (SQL: drop table `contacts`  
>   )                                                                            
>                                                                                
> 
>                                                                                
>   [PDOException]                                                               
>   SQLSTATE[23000]: Integrity constraint violation: 1217 Cannot delete or upda  
>   te a parent row: a foreign key constraint fails

**Comment by Tjoosten** [comment]
@ghermans reproduction steps?

**Comment by ghermans** [comment]
Read above
