### ISSUE TITLE
Server operating system seed

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/Hcrm#134]
Add db seed for the server software operating system. 

- [ ] Add db seed
- [ ] Add `belongsTo` relation.

Relates: #121 
Relates: #133

**Comment by ghermans** [comment]
## Operating list
- CentOS 5 (i386
- CentOS 5 (x86_64)
- CentOS 6 (i386)
- CentOS 6 (x86_64)
- Debian 7.0 (x86)
- Debian 7.0 (x86_64)
- Ubuntu 12.04 (amd64)
- Ubuntu 12.04 (x86)
