### ISSUE TITLE
WEB: Increase padding or margin

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/Hcrm#34]
It woul be nice if we add some padding at the top between the content and navbar. 
<img width="1268" alt="schermafbeelding 2016-06-20 om 15 08 03" src="https://cloud.githubusercontent.com/assets/5157609/16195249/fbc63410-36f8-11e6-8b97-5dc62776cbc5.png">

**Comment by ghermans** [comment]
a breadcrumb-wrapper below the navbar will be added so the margin or padding should not be changed.
