### ISSUE TITLE
WEB & API: Knowledgebase

### ISSUE THREAD

**Issue by ghermans** [idevelopment/Hcrm#9]
Provide answers to common questions and topics to reduce support load.

**Comment by ghermans** [comment]
- Link in navigation bar Support -> **Knowledge base** is not set.
- Link to KB categories in **setup page** is not set.

**Comment by Tjoosten** [comment]
@ghermans what categories u want?

**Comment by ghermans** [comment]
The categories are set dynamically not static.

**Comment by Tjoosten** [comment]
@ghermans ?

**Comment by ghermans** [comment]
@Tjoosten check skype :)

**Comment by Tjoosten** [comment]
@ghermans What KB categories u want?

**Comment by ghermans** [comment]
By default none, or just one simple demo category.

**Comment by Tjoosten** [comment]
@ghermans  categories added. I close this one. If new elements come above water plz open a new issue
