### ISSUE TITLE
Border bug. Ugly gray border

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/Hcrm#93]
There is a spece between the left side and the container. 
The big contains a gray border bewteen the side. And at the right there is no border
<img width="1116" alt="schermafbeelding 2016-07-17 om 22 23 25" src="https://cloud.githubusercontent.com/assets/5157609/16902883/3f983c40-4c6d-11e6-91f5-e93405acf9b7.png">

**Comment by ghermans** [comment]
@Tjoosten what is the resolution on your mac?

**Comment by Tjoosten** [comment]
13 inch

**Comment by Tjoosten** [comment]
<img width="188" alt="schermafbeelding 2016-07-20 om 22 58 18" src="https://cloud.githubusercontent.com/assets/5157609/17002823/7eeab60e-4ecd-11e6-8302-62fcbe62d240.png">
Not fixed!

**Comment by ghermans** [comment]
@Tjoosten can you please check again and give feedback?
